### ISSUE TITLE
OctoPrint Job Return Types

### ISSUE THREAD

**Issue by robweber** [robweber/octoprint-java-lib#2]
per @DataWorm the return values for percentComplete() and getEstimatedPrintTime() use primatives instead of class types as the other methods do. 

Additionally checking the OctoPrint model reference will tell if Double is indeed the correct type here, or if a Long is a better option. 

http://docs.octoprint.org/en/master/api/datamodel.html#sec-api-datamodel-jobs-job

**Comment by robweber** [comment]
It does appear that the EstimatedPrintTime return type is a Long (total time in seconds) while the PercentComplete return type is a float, converted to a Double in the class. 

I started writing some unit tests and did verify this functionality by using the example result on the OctoPrint site. I'll try to confirm on a running job before merging - @DataWorm if you can do this and let me know that would save a step.

**Comment by DataWorm** [comment]
Don't got a real printer yet but I have octoprint running with the virtual device. But something got broken with the user management, I guess I could make a test within this week.

**Comment by robweber** [comment]
No big deal. I can get to it this week too. I'm pretty sure it's fine but best to check.

**Comment by DataWorm** [comment]
I took the time and made some testing. First everything worked fine but at the end of the test print I got an exception:

```
4466038 [octoprint-driver 0] d.i.r.s.d.impl (DriverSchedulerExceptionHandler.java:44)          W Uncatched exception catched from driver instance 'octoprint-driver': java.lang.Long cannot be cast to java.lang.Double
java.lang.ClassCastException: java.lang.Long cannot be cast to java.lang.Double
	at org.octoprint.api.OctoPrintJob$JobProgress.percentComplete(OctoPrintJob.java:79)
	at de.hendrikmotza.iolite.driver.OctoPrintDeviceDataPointFactory.updateJobValues(OctoPrintDeviceDataPointFactory.java:202)
	at de.hendrikmotza.iolite.driver.OctoPrintDeviceDataPointFactory.updateValues(OctoPrintDeviceDataPointFactory.java:180)
	at de.iolite.utilities.concurrency.scheduler.ErrorHandlingRunnable.run(ErrorHandlingRunnable.java:48)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.runAndReset(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```

I guess the problem depends on the json. During the print the progress is usually a real float/double but in the end we just have whole 100%, so there are no decimal parts. Therefore that json library might consider it to be an integer/long and fails to convert it to double directly. I am not familiar with this json library (so far I mainly used jackson) but maybe you have to check for Long/Double first and afterwards cast/convert it the corresponding way.

**Comment by robweber** [comment]
Interesting. I was taking the REST documentation at face value that it would send the type of value indicated (in this case a float). You're probably on to something that it has to do with the JSON parsing. I used simple-json purely because I was trying to keep the footprint low here. 

I think I can modify the method to accept either. Right now I'm simply casting what's returned by the JSONObject class - hence the cast exception. Instead I can do a Double.parseDouble() call and pass the string directly. That way it won't matter. Thanks for taking a look at this.

**Comment by robweber** [comment]
I think everything should be good now. I added a test for the 100% completion issue. Thanks for noticing this.

**Comment by DataWorm** [comment]
I also made another test and so far it seems to work just fine. I guess you also adopted that conversion on other double return types?! Going to make another test within the next week and check whether temperatures and some other data work fine too.

**Comment by robweber** [comment]
I just pushed a bunch of changes that should fix all the casted conversion issues. Any problems during your testing let me know. I also uploaded Javadocs to Github (link in README) so it should be more clear how to perform certain actions.
